Redux navigation integration functioning
redspanner/go-for-eat-client pull request #8
Opened 2018-01-30 16:03 UTC by redspanner

2018-01-30 17:25 UTC, arol commented on go-for-eat/actions/index.js
> +const userArraySchema = [userSchema];
Ract Navigation and some bonus tracks!

2018-01-30 17:25 UTC, arol commented on go-for-eat/navigation/index.js
> +  CreateEvent: {
Sorry, doesn't it mean that CreateEvent is now part of the `HomeStack` so it will be pushed when presented?

2018-01-30 17:25 UTC, arol commented on go-for-eat/navigation/index.js
> +  CreateEvent: {
I imagined it to be something like
`NavigatorWithModal(NavigatorWithRootScreen(MainNavigator), CreateEvent)`

2018-01-30 17:25 UTC, arol commented on go-for-eat/screens/Login/Login.js
> +  goHome: () => dispatch({type:'Home'})
I suggest naming the action to something more specific like `'navigation.home'`

2018-01-30 17:29 UTC, arol approved these changes

2018-01-31 12:15 UTC, arol requested changes

2018-01-31 12:15 UTC, arol commented on go-for-eat/components/NavBar/NavBar.js
> +    new Promise((resolve,reject) => {
Why? :(
This will resolve immediately.

2018-01-31 12:15 UTC, arol commented on go-for-eat/components/NavBar/NavBar.js
> +  // renderButton = (onPress, icon) => {
Remove unused code.

2018-01-31 12:15 UTC, arol commented on go-for-eat/components/NavBar/NavBar.js
> +    // const buttons={}
Remove unused/commented code.

2018-01-31 12:15 UTC, arol commented on go-for-eat/localStorage.js
> +    Expo.SecureStore.setItemAsync('state', serializedState);
If you return this, you'll make logoutStorage to be an asynchronous operation.
And the try catch in the level above, so next to the business logic.

2018-01-31 13:15 UTC, redspanner commented on go-for-eat/components/NavBar/NavBar.js
> +    new Promise((resolve,reject) => {
:(

2018-01-31 16:00 UTC, arol approved these changes

2018-01-31 16:00 UTC, arol commented on go-for-eat/components/NavBar/NavBar.js
> +  handleLogout = () => {
```js
handleLogout = async () => {
    const serializedState = JSON.stringify({});
    await Expo.SecureStore.setItemAsync('state', serializedState);
    await this.props.logoutState(); // if async
    this.props.navigate('Login');
}
```

2018-01-31 18:44 UTC, div-Leo approved these changes
just for this time

2018-01-31 18:44 UTC, merged